language: node_js
node_js:
  - 5.1.0

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm@latest

after_success:
  - npm run coverage

notifications:
  email: false
  slack:
    secure: Igr4ROglzIdbPkL9MgMBl3+YFbDaVuOf9PWSnRkoNOFQgmecc+jIwdpKC8772zZnYdUvV9tQgblL0OChbyL5RYxrCTD1uoLY6p60abFz5x+Vy/SBVk5+1D9vFqVHUmj9n19Ilnrr/Wywu3ESEr5vlBQe/b/GvnfrRNohkgFMS0ky/U5P7YxgUiHR4kLHOFvbbxm0gLI7E5c3rZDDvibH/nbIBQV4T+U46a/+Ruz9RgsawId0l9ey5CrV9Si75dAc72kfFcUc5Qrg7CEVMztXTdehERkWxLGl8YGbuWAbb335lJmtIkiPUYQYAFBkn8Mnra/baV7BHpbH+TmCbIA3PeGBoJXFx55eMmHe8h9I6OZJDzQ4C1F2PQ+C3MOw99n0g77/OhKm4wh6BuIg4+5saXQtkrWd9AWWZEGHwYJ+MRrGi+5P78tSFDYd8UWyw5xAWVUJniwg4AKLLlsIb4uV5ZuuGkeuOx/EFOF5G+tKfrFxcWx+vUmgbcg5xR801uSdiW12k2/yUy9fDoPJn9f2KhHfhg5QJP6mPPQ+R7kR4C0f/QhhZzQ98h3DR0uqZbXiYWTtFhbC7t+sc50tB9nOCK29nigsYuiS2d64QZ51sbTs8YGM9EvjE9AY0NhHLMfUGCeExzAdjJMtFTcHIBjMvsBqRmBSJYyKVJCLt3Ynq/Q=
