language: node_js
node_js:
  - 5.1.0

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm@latest

after_success:
  - npm run codecov

notifications:
  email: false

deploy:
  provider: heroku
  api_key:
    secure: GjoEf7UFJFBW4hE1Zy84Ny9ajPiF5jFFTVpPrvUwqJXehNx5Sq6/nln+cijgFauTG6T5bHt7A5mEvbrNyYwIP4jnkrnIS8dL8ohNH/brWFHYVwpeQosgyvpdoPEvitImBrT9UIcUBgnnRk6biqNk4oT14LwhLGdgLDAzMsAAMbV8X/DdXQBUH//UPhfeRQ6jppe77k8khuMCWoa1ZQjMX8GKXHjhA/TFjb36Ml8BElVto/ASllAkVazwgc7KQgIMTFAP6jTSfTLr5hP1yYqBphPGLF7DHqeeTV8hwAr95rTcbdJN8oqZp1L2tA26oAMCnP+k1fjQ/YbpsEdvqOQhWxs7Z59ai+zdd3NgEmZeVm8VLSaywgbhudrgVQX2c5jSYJ4IscJEIXzpnvDB14F4Luk5PO6yzSPNaljOHLuKhS3pOjWIvmggNZew0enNMs1N9syAGL3eQApive32Sj94ypSLrjyFo5wb8OaFm/S2x39dsuD3CKsXjVJkc172ERaHyKe6d8K7RJ65BzCThW4406IbI98rEHm6L8aax/RpBRMb/O/nNJRzb9QUBWSosHqVgx5mTS04YTD6ltZiYnfUrqgeDIF+oYlHJXylAOjzRWtgZLLhUoPKYRNOKCG8YDOGX3bQ5moWBmX0lXCGvfkFeEah/+VAjQ2Viixm6zGdyNQ=
  app: web-app-starter-kit
  on: master
