web:
  build: .
  command: 'bash -c ''node dist/server.js'''
  working_dir: /app/user
  environment:
    PORT: 3000
    DEBUG: app:*
  ports:
    - '80:3000'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 3000
    DEBUG: app:*
  ports:
    - '80:3000'
  volumes:
    - '.:/app/user'

